In [1]:
import pandas as pd 
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt

url = 'https://storage.googleapis.com/kaggle-forum-message-attachments/237294/7771/german_credit_data.csv'
df = pd.read_csv(url)

In [2]:
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_').str.replace('(', '').str.replace(')', '')

df['saving_accounts'] = df['saving_accounts'].fillna(df['saving_accounts'].value_counts().idxmax())
df['checking_account'] = df['checking_account'].fillna(df['checking_account'].value_counts().idxmax())

In [3]:
from sklearn.preprocessing import LabelEncoder
df['sex'] = LabelEncoder().fit_transform(df['sex'])
df['housing'] = LabelEncoder().fit_transform(df['housing'])
df['purpose'] = LabelEncoder().fit_transform(df['purpose'])
df['risk'] = LabelEncoder().fit_transform(df['risk'])
df['saving_accounts'] = LabelEncoder().fit_transform(df['saving_accounts'])
df['checking_account'] = LabelEncoder().fit_transform(df['checking_account'])


df

,unnamed:_0,age,sex,job,housing,saving_accounts,checking_account,credit_amount,duration,purpose,risk
0,0,67,1,2,1,0,0,1169,6,5,1
1,1,22,0,2,1,0,1,5951,48,5,0
2,2,49,1,1,1,0,0,2096,12,3,1
3,3,45,1,2,0,0,0,7882,42,4,1
4,4,53,1,2,0,0,0,4870,24,1,0
5,5,35,1,1,0,0,0,9055,36,3,1
6,6,53,1,2,1,2,0,2835,24,4,1
7,7,35,1,3,2,0,1,6948,36,1,1
8,8,61,1,1,1,3,0,3059,12,5,1
9,9,28,1,3,1,0,1,5234,30,1,0
10,10,25,0,2,2,0,1,1295,12,1,0
11,11,24,0,2,2,0,0,4308,48,0,0
12,12,22,0,2,1,0,1,1567,12,5,1
13,13,60,1,1,1,0,0,1199,24,1,0
14,14,28,0,2,2,0,0,1403,15,1,1
15,15,32,0,1,1,1,0,1282,24,5,0
16,16,53,1,2,1,0,0,2424,24,5,1
17,17,25,1,2,1,0,0,8072,30,0,1
18,18,44,0,3,0,0,1,12579,24,1,0
19,19,31,1,2,1,2,0,3430,24,5,1
20,20,48,1,2,1,0,0,2134,9,1,1
21,21,44,1,2,2,2,0,2647,6,5,1
22,22,48,1,1,2,0,0,2241,10,1,1
23,23,44,1,2,1,1,1,1804,12,1,1
24,24,26,1,2,1,0,0,2069,10,4,1
25,25,36,1,1,1,0,0,1374,6,4,1
26,26,39,1,1,1,0,0,426,6,5,1
27,27,42,0,2,2,3,2,409,12,5,1
28,28,34,1,2,1,0,1,2415,7,5,1
29,29,63,1,2,1,0,0,6836,60,0,0
...,...,...,...,...,...,...,...,...,...,...,...
970,970,22,1,2,1,1,1,1514,15,6,1
971,971,43,1,1,1,0,0,7393,24,1,1
972,972,29,0,0,2,0,0,1193,24,1,0
973,973,36,1,2,2,0,0,7297,60,0,0
974,974,33,0,2,1,0,0,2831,30,5,1
975,975,57,0,1,1,2,2,1258,24,5,1
976,976,64,0,2,1,0,1,753,6,5,1
977,977,42,1,2,1,0,1,2427,18,0,1
978,978,47,1,1,1,0,0,2538,24,1,0
979,979,25,1,2,2,1,1,1264,15,1,0
980,980,49,1,2,1,0,1,8386,30,4,0
981,981,33,1,3,2,0,0,4844,48,0,0
982,982,28,0,3,1,1,2,2923,21,1,1
983,983,26,1,2,1,0,0,8229,36,1,0
984,984,30,1,1,1,0,0,2028,24,4,1
985,985,25,0,2,2,0,0,1433,15,4,1
986,986,33,1,2,1,0,2,6289,42,0,1
987,987,64,0,2,1,1,0,1409,13,5,1
988,988,29,1,3,0,0,0,6579,24,1,1
989,989,48,1,1,1,0,1,1743,24,5,1
990,990,37,1,1,1,0,0,3565,12,3,1
991,991,34,1,1,1,1,0,1569,15,5,1
992,992,23,1,1,2,0,0,1936,18,5,1
993,993,30,1,3,1,0,0,3959,36,4,1
994,994,50,1,2,1,0,0,2390,12,1,1
995,995,31,0,1,1,0,0,1736,12,4,1
996,996,40,1,3,1,0,0,3857,30,1,1
997,997,38,1,2,1,0,0,804,12,5,1
998,998,23,1,2,0,0,0,1845,45,5,0
999,999,27,1,2,1,1,1,4576,45,1,1

In [4]:
x = df.iloc[:, :-1].values
y = df.iloc[:, 10].values

In [5]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20)

In [6]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x_train)

x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [10]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score

classifier = KNeighborsClassifier(n_neighbors=7)
classifier.fit(x_train, y_train)


y_pred = classifier.predict(x_test)


from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print("--------------------")
print("accuracy score:")
print(accuracy_score(y_test, y_pred))

print("--------------------")
print("cross validation score:")
print(cross_val_score(classifier, x, y, cv=5))

print("--------------------")
print("confusion matrix:")
print(confusion_matrix(y_test, y_pred))

print("--------------------")
print("classification report:")
print(classification_report(y_test, y_pred))
print("--------------------")

--------------------
accuracy score:
0.7
--------------------
cross validation score:
[0.69  0.66  0.555 0.565 0.68 ]
--------------------
confusion matrix:
[[ 15  47]
 [ 13 125]]
--------------------
classification report:
              precision    recall  f1-score   support

           0       0.54      0.24      0.33        62
           1       0.73      0.91      0.81       138

    accuracy                           0.70       200
   macro avg       0.63      0.57      0.57       200
weighted avg       0.67      0.70      0.66       200

--------------------